name: Build and Deploy Docker Image to Docker Hub

on:
  push:
    branches:
      - main # Jalankan CI/CD saat ada perubahan di branch `main`

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout kode dari repositori
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (untuk build multi-arch jika dibutuhkan)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in ke Docker Hub menggunakan GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Menggunakan Docker Hub username dari Secrets
          password: ${{ secrets.DOCKER_TOKEN }} # Menggunakan Docker Hub token dari Secrets

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t neverez/valentine-web:1.0.0 .

      # Step 5: Push Docker Image ke Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push neverez/valentine-web:1.0.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Step 1: Install SSH key from GitHub Secrets
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Step 2: Deploy to AWS EC2
      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            # Login ke Docker Hub dengan credentials
            docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"

            # Tarik Docker image terbaru
            docker pull neverez/valentine-web:1.0.0

            # Stop dan hapus container yang lama jika ada
            docker stop valentine-web || true
            docker rm valentine-web || true

            # Jalankan container baru dengan port yang diinginkan
            docker run -d --name valentine-web -p 80:3000 neverez/valentine-web:latest
          EOF
