name: Build and Deploy Docker Image to Docker Hub

on:
  push:
    branches:
      - main # Jalankan CI/CD saat ada perubahan di branch `main`

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout kode dari repositori
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (untuk build multi-arch jika dibutuhkan)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Log in ke Docker Hub menggunakan GitHub Secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Menggunakan Docker Hub username dari Secrets
          password: ${{ secrets.DOCKER_TOKEN }} # Menggunakan Docker Hub token dari Secrets

      # Step 4: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t neverez/valentine-web:1.0.0 .

      # Step 5: Push Docker Image ke Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push neverez/valentine-web:1.0.0

  # (Opsional) Deploy Step jika Anda ingin deploy otomatis ke server setelah push image
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Deploy to Server (Opsional)
  #       run: |
  #         # Jika Anda ingin deploy ke server, misalnya menggunakan SSH:
  #         ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
  #           docker pull nextjs-project/valentine-web:1.0.1
  #           docker stop valentine-web || true
  #           docker rm valentine-web || true
  #           docker run -d --name valentine-web -p 80:80 nextjs-project/valentine-web:1.0.1
  #         EOF
